config:
  backup: true
  create: true
  dotpath: dotfiles
  minversion: 1.13.2
dotfiles:
  f_mise.toml:
    src: mise.toml
    dst: ~/.mise.toml
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_alacritty.toml:
    src: config/alacritty/alacritty.toml
    dst: ~/.config/alacritty/alacritty.toml
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_config:
    src: config/pgcli/config
    dst: ~/.config/pgcli/config
  f_ssh_private:
    dst: ~/.ssh/itsalex
    src: ssh/itsalex
    chmod: '600'
    trans_install: _gpg
  f_ssh_public:
    dst: ~/.ssh/itsalex.pub
    src: ssh/itsalex.pub
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  f_wallpaper.jpg:
    src: Pictures/wallpaper.jpg
    dst: ~/Pictures/wallpaper.jpg
  f_space_bg.jpg:
    src: Pictures/space_bg.jpg
    dst: ~/Pictures/space_bg.jpg
  f_npmrc:
    src: npmrc
    dst: ~/.npmrc
  f_use_mise.sh:
    src: config/direnv/lib/use_mise.sh
    dst: ~/.config/direnv/lib/use_mise.sh
  f_settings.toml:
    src: config/mise/settings.toml
    dst: ~/.config/mise/settings.toml
  f_dracula.toml:
    src: config/alacritty/dracula.toml
    dst: ~/.config/alacritty/dracula.toml
profiles:
  linux-gnome:
    dotfiles:
    - f_mise.toml
    - f_gitconfig
    - f_alacritty.toml
    - f_zshrc
    - f_tmux.conf
    - f_config
    - f_ssh_private
    - f_ssh_public
    - f_ssh_config
    - f_wallpaper.jpg
    - f_space_bg.jpg
    - f_npmrc
    - f_use_mise.sh
    - f_settings.toml
    - f_dracula.toml
  macos:
    dotfiles:
    - f_mise.toml
    - f_gitconfig
    - f_alacritty.toml
    - f_zshrc
    - f_tmux.conf
    - f_config
    - f_ssh_private
    - f_ssh_public
    - f_ssh_config
    - f_space_bg.jpg
    - f_npmrc
    - f_use_mise.sh
    - f_settings.toml
trans_install:
  _gpg: gpg2 -q --for-your-eyes-only --no-tty -d {0} > {1}
