# Colors (Dracula)
import = ["~/.config/alacritty/dracula.toml"]

{%@@ if profile == "macos" @@%}
[font]
size = 12.0

[font.bold]
family = "Monaco"
style = "Bold"

[font.bold_italic]
family = "Monaco"
style = "Bold Italic"

[font.italic]
family = "Monaco"
style = "Italic"

[font.normal]
family = "Monaco"
{%@@ elif profile == "linux-gnome" @@%}
[font]
size = 9.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
{%@@ endif @@%}

[shell]
{%@@ if profile == "macos" @@%}
args = ["-l", "-c", "source ~/.zshrc; tmux attach 2> /dev/null || tmux"]
program = "/opt/homebrew/bin/zsh"
{%@@ elif profile == "linux-gnome" @@%}
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/bash"
{%@@ endif @@%}
